# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: observation_decision.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aobservation_decision.proto\x12\x14observation_decision\"2\n\x0bObservation\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05state\x18\x03 \x01(\x05\"\x18\n\x06\x41\x63tion\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32X\n\x08\x44\x65\x63ision\x12L\n\tGetAction\x12!.observation_decision.Observation\x1a\x1c.observation_decision.Actionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'observation_decision_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBSERVATION']._serialized_start=52
  _globals['_OBSERVATION']._serialized_end=102
  _globals['_ACTION']._serialized_start=104
  _globals['_ACTION']._serialized_end=128
  _globals['_DECISION']._serialized_start=130
  _globals['_DECISION']._serialized_end=218
# @@protoc_insertion_point(module_scope)
