# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import observation_decision_pb2 as observation__decision__pb2


class DecisionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAction = channel.unary_unary(
                '/observation_decision.Decision/GetAction',
                request_serializer=observation__decision__pb2.Observation.SerializeToString,
                response_deserializer=observation__decision__pb2.Action.FromString,
                )


class DecisionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAction,
                    request_deserializer=observation__decision__pb2.Observation.FromString,
                    response_serializer=observation__decision__pb2.Action.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'observation_decision.Decision', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Decision(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/observation_decision.Decision/GetAction',
            observation__decision__pb2.Observation.SerializeToString,
            observation__decision__pb2.Action.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
